# Generated by Django 4.0 on 2021-12-13 09:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_product_in_stock_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='I can marry Erastus anytime anywhere.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Test Product - 52 ', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(choices=[('F', 'ETBM'), ('N', 'EMU'), ('P', 'ETBM')], max_length=200),
        ),
    ]
