# Generated by Django 4.0 on 2021-12-13 09:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_product_description_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='Wow! I have never seen anything like this before.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Test Product - 100 ', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(choices=[('F', 'ETBM'), ('N', 'EMU'), ('P', 'ETBM')], default='EMU', max_length=200),
        ),
    ]
