# Generated by Django 4.0 on 2021-12-17 11:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_remove_product_thumbnail_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='I love this product so much.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Test Product - 10 ', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='sizes', to='src.Size'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(help_text='Enter a valid reason for requesting a refund.', verbose_name='Reason for requesting a refund'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='ref_code',
            field=models.CharField(help_text='Enter a valid reference code.', max_length=200, verbose_name='Reference code'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='articles', to='src.ArticleCategory')),
            ],
        ),
    ]
