# Generated by Django 4.0 on 2021-12-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_alter_articlecategory_options_article_slug_and_more'),
        ('src', '0013_alter_product_description_alter_product_name'),
    ]

    operations = [
    ]
